apiVersion: v1
kind: ReplicationController
metadata:
  name: rollingout
spec:
  replicas: 300
  selector:
    app: rollingout
  template:
    metadata:
      name: rollingout
      labels:
        app: rollingout
    spec:
      containers:
        - name: rollingout
          image: gar7mn/roll
          ports:
            - containerPort: 8080
