apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rollingout
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rollingout
  minReplicas: 64
  maxReplicas: 128
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
        
